### ISSUE TITLE
KeyCloak configuration

### ISSUE THREAD

**Issue by DejanPopovic1** [tuxiem/AspNetCore-keycloak#7]
Whilst I get the project to compile, I consistently get an access denied error. This leads me to believe that something is not configured correctly on the keycloak console side. The readme doesnt contain what to actually configure with regards to roles, policies, claims, etc. The only mention of this is the Role Mapper but nothing else. Can you please provide how to configure a user in its entirety over and above the role mapper?

**Comment by tuxiem** [comment]
Have you tried to look at the JWT?
Use jwt.io to debug, there are comments in the code you need to uncomment and insert a breakpoint.

If that doesn't point you in the right direction I need more info on your setup.
Screenshots or code dumps.

**Comment by pgrondin27** [comment]
@DejanPopovic1 I just submitted a PR to make debugging roles a bit easier. Check the following files.
- HomeController.cs : Set AuthenticationAsync requirement to Authorize. Does not depend on role anymore to allow you to see the User page.
- Authentication.cshtml : Add list of of UserRoles extracted from Keycloak/OpenId handshake in the User page.
Hope this helps.
